#!/bin/bash

# Test for color support
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null
then
  # We have color support; assume it's compliant with Ecma-48 (ISO/IEC-6429)
  # Lack of such support is extremely rare, and such a case would tend to
  # support setf rather than setaf
  color_prompt=yes
else
  color_prompt=no
fi

if [ "$color_prompt" = yes ]
then
  RED="\[\033[01;31m\]"
  GREEN="\[\033[01;32m\]"
  YELLOW="\[\033[01;33m\]"
  BLUE="\[\033[01;34m\]"
  NC="\[\033[00m\]"
fi

# Clear local variable
unset color_prompt
