#!/bin/bash

# Add ccache before other compiler so that it's the one taken
export PATH=/usr/lib/ccache/:$PATH

# Set CPU number
export CPU_COUNT=`grep -i processor /proc/cpuinfo | wc -l`

export EDITOR=vim
export XML_CATALOGS_FILES=/etc/xml/catalog
