#!/bin/bash

export PATH=/snap/bin:$PATH
# User ~/.local/bin and ~/bin directories ar not in the path by default on most system
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH
# Add ccache before other compiler so that it's the one taken
export PATH=/usr/lib/ccache:$PATH

# Set CPU number
export CPU_COUNT=`nproc`

# Use most as pager (especially for man display) if available
[ `which most` ] && export PAGER=most

# Misc
export EDITOR=vim
export XML_CATALOGS_FILES=/etc/xml/catalog
export NINJA_STATUS="[%p][%s/%t] "
export CMAKE_GENERATOR="Ninja"
export CMAKE_COLOR_DIAGNOSTICS=ON
export CTEST_OUTPUT_ON_FAILURE=1
export CTEST_PROGRESS_OUTPUT=1
export RSH_RETRY=0

