#!/bin/bash

function parse_git_branch
{
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function parse_git_status
{
  notclean=`git status --porcelain 2> /dev/null | grep -E "^.(??|M|A|D|R|C|U)" | wc -l`

  if [[ $notclean -gt 0 ]]; then echo -n "*"; fi
}

GIT_STATUS="\$(parse_git_branch)\$(parse_git_status)"
