#!/bin/bash

if [ -r /etc/bash_completion.d/ctest ]
then
  . /etc/bash_completion.d/ctest
  eval "`complete -p ctest | sed 's/ ctest$//'` ctestj"
elif [ -r /usr/share/bash-completion/completions/ctest ]
then
  . /usr/share/bash-completion/completions/ctest
  eval "`complete -p ctest | sed 's/ ctest$//'` ctestj"
fi
