#!/bin/bash

function _wllppr()
{
  local current="${COMP_WORDS[COMP_CWORD]}"
  local previous="${COMP_WORDS[COMP_CWORD-1]}"

  case $previous in
    wllppr) COMPREPLY=(`compgen -W "db up help" -- $current`) ;;
    *) COMPREPLY=();;
  esac
}

complete -F _wllppr wllppr

